version : '3'
services:
  portal:
    container_name: devsecops
    image: devsecops_image
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
  mysql:
    image: joychou/jsc_mysql:latest
    ports:
      - "3306:3306"
networks: 
  default: 
    external: 
      name: net